[package]
name = "mask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-bert = "0.17.0"
anyhow = "1.0.55"
tch = "0.6.1"
rust_tokenizers = "7.0.1"
